# **********************************************************************
#
# Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
#
# This copy of Ice is licensed to you under the terms described in the
# ICE_LICENSE file included in this distribution.
#
# **********************************************************************
#
# Ice version 3.5.1
#
# <auto-generated>
#
# Generated from file `IceSRTClient.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

import Ice, IcePy

# Start of module SRTClient
_M_SRTClient = Ice.openModule('SRTClient')
__name__ = 'SRTClient'

if 'Client' not in _M_SRTClient.__dict__:
    _M_SRTClient.Client = Ice.createTempClass()
    class Client(Ice.Object):
        def __init__(self):
            if Ice.getType(self) == _M_SRTClient.Client:
                raise RuntimeError('SRTClient.Client is an abstract class')

        def ice_ids(self, current=None):
            return ('::Ice::Object', '::SRTClient::Client')

        def ice_id(self, current=None):
            return '::SRTClient::Client'

        def ice_staticId():
            return '::SRTClient::Client'
        ice_staticId = staticmethod(ice_staticId)

        def message(self, s, current=None):
            pass

        def setup(self, current=None):
            pass

        def trackSource(self, s, current=None):
            pass

        def stopTrack(self, current=None):
            pass

        def __str__(self):
            return IcePy.stringify(self, _M_SRTClient._t_Client)

        __repr__ = __str__

    _M_SRTClient.ClientPrx = Ice.createTempClass()
    class ClientPrx(Ice.ObjectPrx):

        def message(self, s, _ctx=None):
            return _M_SRTClient.Client._op_message.invoke(self, ((s, ), _ctx))

        def begin_message(self, s, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_SRTClient.Client._op_message.begin(self, ((s, ), _response, _ex, _sent, _ctx))

        def end_message(self, _r):
            return _M_SRTClient.Client._op_message.end(self, _r)

        def setup(self, _ctx=None):
            return _M_SRTClient.Client._op_setup.invoke(self, ((), _ctx))

        def begin_setup(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_SRTClient.Client._op_setup.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_setup(self, _r):
            return _M_SRTClient.Client._op_setup.end(self, _r)

        def trackSource(self, s, _ctx=None):
            return _M_SRTClient.Client._op_trackSource.invoke(self, ((s, ), _ctx))

        def begin_trackSource(self, s, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_SRTClient.Client._op_trackSource.begin(self, ((s, ), _response, _ex, _sent, _ctx))

        def end_trackSource(self, _r):
            return _M_SRTClient.Client._op_trackSource.end(self, _r)

        def stopTrack(self, _ctx=None):
            return _M_SRTClient.Client._op_stopTrack.invoke(self, ((), _ctx))

        def begin_stopTrack(self, _response=None, _ex=None, _sent=None, _ctx=None):
            return _M_SRTClient.Client._op_stopTrack.begin(self, ((), _response, _ex, _sent, _ctx))

        def end_stopTrack(self, _r):
            return _M_SRTClient.Client._op_stopTrack.end(self, _r)

        def checkedCast(proxy, facetOrCtx=None, _ctx=None):
            return _M_SRTClient.ClientPrx.ice_checkedCast(proxy, '::SRTClient::Client', facetOrCtx, _ctx)
        checkedCast = staticmethod(checkedCast)

        def uncheckedCast(proxy, facet=None):
            return _M_SRTClient.ClientPrx.ice_uncheckedCast(proxy, facet)
        uncheckedCast = staticmethod(uncheckedCast)

    _M_SRTClient._t_ClientPrx = IcePy.defineProxy('::SRTClient::Client', ClientPrx)

    _M_SRTClient._t_Client = IcePy.defineClass('::SRTClient::Client', Client, -1, (), True, False, None, (), ())
    Client._ice_type = _M_SRTClient._t_Client

    Client._op_message = IcePy.Operation('message', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (((), IcePy._t_string, False, 0),), None, ())
    Client._op_setup = IcePy.Operation('setup', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (((), IcePy._t_string, False, 0),), None, ())
    Client._op_trackSource = IcePy.Operation('trackSource', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (((), IcePy._t_string, False, 0),), None, ())
    Client._op_stopTrack = IcePy.Operation('stopTrack', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (), (((), IcePy._t_string, False, 0),), None, ())

    _M_SRTClient.Client = Client
    del Client

    _M_SRTClient.ClientPrx = ClientPrx
    del ClientPrx

# End of module SRTClient
